// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFmpz0GnB4yrx6tQcOBhIbY2BKsdmlhIc',
    appId: '1:422340379390:web:f3120369c74c5764399baf',
    messagingSenderId: '422340379390',
    projectId: 'empacaduras-calc-daniel-01',
    authDomain: 'empacaduras-calc-daniel-01.firebaseapp.com',
    storageBucket: 'empacaduras-calc-daniel-01.firebasestorage.app',
    measurementId: 'G-J7XB5KWJ04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopXrtiK35poauYXBPSb9JiQgYfkcnHIk',
    appId: '1:422340379390:android:38f0fc7334e41318399baf',
    messagingSenderId: '422340379390',
    projectId: 'empacaduras-calc-daniel-01',
    storageBucket: 'empacaduras-calc-daniel-01.firebasestorage.app',
  );
}
